apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-default
  labels:
    app: tomcat
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: ny726/tomcat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
